//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drosy.Domain.Shared.ErrorComponents.Attendence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_Attendance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_Attendance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drosy.Domain.Shared.ErrorComponents.Attendence.Resources.ErrorMessages.Attendance" +
                            "", typeof(ErrorMessages_Attendance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance has already been recorded..
        /// </summary>
        internal static string Error_Attendence_AlreadyExists {
            get {
                return ResourceManager.GetString("Error_Attendence_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save attendance. Please try again..
        /// </summary>
        internal static string Error_Attendence_CannotSaveChanges {
            get {
                return ResourceManager.GetString("Error_Attendence_CannotSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some attendance records already exist and caused a conflict..
        /// </summary>
        internal static string Error_Attendence_ConflictOnBatchAdd {
            get {
                return ResourceManager.GetString("Error_Attendence_ConflictOnBatchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session ID is invalid..
        /// </summary>
        internal static string Error_Attendence_InvalidSessionId {
            get {
                return ResourceManager.GetString("Error_Attendence_InvalidSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attendance status is invalid..
        /// </summary>
        internal static string Error_Attendence_InvalidStatus {
            get {
                return ResourceManager.GetString("Error_Attendence_InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student ID is invalid..
        /// </summary>
        internal static string Error_Attendence_InvalidStudentId {
            get {
                return ResourceManager.GetString("Error_Attendence_InvalidStudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance record not found..
        /// </summary>
        internal static string Error_Attendence_NotFound {
            get {
                return ResourceManager.GetString("Error_Attendence_NotFound", resourceCulture);
            }
        }
    }
}
