//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drosy.Domain.Shared.ErrorComponents.Payments.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drosy.Domain.Shared.ErrorComponents.Payments.Resources.ErrorMessages.Payment", typeof(ErrorMessages_Payment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون مبلغ الدفع أكبر من صفر..
        /// </summary>
        internal static string Error_Payment_AmountMustBePositive {
            get {
                return ResourceManager.GetString("Error_Payment_AmountMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  حدث انتهاك لقيد البيانات أثناء عملية الدفع..
        /// </summary>
        internal static string Error_Payment_ConstraintViolation {
            get {
                return ResourceManager.GetString("Error_Payment_ConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد تاريخ الدفع..
        /// </summary>
        internal static string Error_Payment_DateRequired {
            get {
                return ResourceManager.GetString("Error_Payment_DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يُسمح بتكرار نفس الدفع..
        /// </summary>
        internal static string Error_Payment_DuplicateNotAllowed {
            get {
                return ResourceManager.GetString("Error_Payment_DuplicateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ الدفع يتجاوز الرصيد المستحق..
        /// </summary>
        internal static string Error_Payment_ExceedsOutstandingBalance {
            get {
                return ResourceManager.GetString("Error_Payment_ExceedsOutstandingBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نطاق تاريخ غير صالح: يجب أن يكون تاريخ البداية قبل أو يساوي تاريخ النهاية..
        /// </summary>
        internal static string Error_Payment_InvalidDateRange {
            get {
                return ResourceManager.GetString("Error_Payment_InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يُسمح بتعديل الدفع..
        /// </summary>
        internal static string Error_Payment_ModificationNotAllowed {
            get {
                return ResourceManager.GetString("Error_Payment_ModificationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على سجل الدفع..
        /// </summary>
        internal static string Error_Payment_NotFound {
            get {
                return ResourceManager.GetString("Error_Payment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يجب تحديد طريقة الدفع..
        /// </summary>
        internal static string Error_Payment_PaymentMethodRequired {
            get {
                return ResourceManager.GetString("Error_Payment_PaymentMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في حفظ بيانات الدفع..
        /// </summary>
        internal static string Error_Payment_SaveFailure {
            get {
                return ResourceManager.GetString("Error_Payment_SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد الطالب المرتبط بالدفع..
        /// </summary>
        internal static string Error_Payment_StudentRequired {
            get {
                return ResourceManager.GetString("Error_Payment_StudentRequired", resourceCulture);
            }
        }
    }
}
