//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drosy.Domain.Shared.ErrorComponents.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages_Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drosy.Domain.Shared.ErrorComponents.Common.Resources.ErrorMessages.Common", typeof(ErrorMessages_Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الإجراء يخالف قاعدة من قواعد العمل..
        /// </summary>
        public static string Error_Common_BusinessRule {
            get {
                return ResourceManager.GetString("Error_Common_BusinessRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  حدث تعارض أثناء معالجة الطلب..
        /// </summary>
        public static string Error_Common_Conflict {
            get {
                return ResourceManager.GetString("Error_Common_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع. يرجى المحاولة لاحقًا..
        /// </summary>
        public static string Error_Common_Failure {
            get {
                return ResourceManager.GetString("Error_Common_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات المقدمة غير صالحة..
        /// </summary>
        public static string Error_Common_Invalid {
            get {
                return ResourceManager.GetString("Error_Common_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على المورد المطلوب..
        /// </summary>
        public static string Error_Common_NotFound {
            get {
                return ResourceManager.GetString("Error_Common_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تقديم قيمة فارغة..
        /// </summary>
        public static string Error_Common_NullValue {
            get {
                return ResourceManager.GetString("Error_Common_NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء العملية..
        /// </summary>
        public static string Error_Common_OperationCancelled {
            get {
                return ResourceManager.GetString("Error_Common_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لتنفيذ هذا الإجراء..
        /// </summary>
        public static string Error_Common_Unauthorized {
            get {
                return ResourceManager.GetString("Error_Common_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ غير متوقع..
        /// </summary>
        public static string Error_Common_Unexpected {
            get {
                return ResourceManager.GetString("Error_Common_Unexpected", resourceCulture);
            }
        }
    }
}
