//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drosy.Domain.Shared.ErrorComponents.Plans.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_Plan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_Plan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drosy.Domain.Shared.ErrorComponents.Plans.Resources.ErrorMessages.Plan", typeof(ErrorMessages_Plan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انتهاك أحد قيود قاعدة البيانات أثناء معالجة الخطة..
        /// </summary>
        internal static string Error_Plan_ConstraintViolation {
            get {
                return ResourceManager.GetString("Error_Plan_ConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار يوم واحد على الأقل من أيام الأسبوع..
        /// </summary>
        internal static string Error_Plan_DaysOfWeekRequired {
            get {
                return ResourceManager.GetString("Error_Plan_DaysOfWeekRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الانتهاء مطلوب..
        /// </summary>
        internal static string Error_Plan_EndDateRequired {
            get {
                return ResourceManager.GetString("Error_Plan_EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت انتهاء الجلسة مطلوب..
        /// </summary>
        internal static string Error_Plan_EndSessionRequired {
            get {
                return ResourceManager.GetString("Error_Plan_EndSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء يجب أن يكون قبل تاريخ الانتهاء..
        /// </summary>
        internal static string Error_Plan_InvalidDateRange {
            get {
                return ResourceManager.GetString("Error_Plan_InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت البدء يجب أن يكون قبل وقت الانتهاء..
        /// </summary>
        internal static string Error_Plan_InvalidSessionTimeRange {
            get {
                return ResourceManager.GetString("Error_Plan_InvalidSessionTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف خطة تحتوي على طلاب مسجلين..
        /// </summary>
        internal static string Error_Plan_PlanCannotDeleteWithStudents {
            get {
                return ResourceManager.GetString("Error_Plan_PlanCannotDeleteWithStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطة غير مفعلة ولا يمكن استخدامها..
        /// </summary>
        internal static string Error_Plan_PlanInactive {
            get {
                return ResourceManager.GetString("Error_Plan_PlanInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطة المطلوبة غير موجودة..
        /// </summary>
        internal static string Error_Plan_PlanNotFound {
            get {
                return ResourceManager.GetString("Error_Plan_PlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في حفظ الخطة. يرجى المحاولة مرة أخرى..
        /// </summary>
        internal static string Error_Plan_PlanSaveFailure {
            get {
                return ResourceManager.GetString("Error_Plan_PlanSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الخطة غير مدعوم..
        /// </summary>
        internal static string Error_Plan_PlanTypeNotSupported {
            get {
                return ResourceManager.GetString("Error_Plan_PlanTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجد خطة أخرى بنفس توقيت الجلسة في الأيام المحددة..
        /// </summary>
        internal static string Error_Plan_SessionTimeConflict {
            get {
                return ResourceManager.GetString("Error_Plan_SessionTimeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء مطلوب..
        /// </summary>
        internal static string Error_Plan_StartDateRequired {
            get {
                return ResourceManager.GetString("Error_Plan_StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت بدء الجلسة مطلوب..
        /// </summary>
        internal static string Error_Plan_StartSessionRequired {
            get {
                return ResourceManager.GetString("Error_Plan_StartSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي الرسوم يجب أن يكون أكبر من صفر..
        /// </summary>
        internal static string Error_Plan_TotalFeesMustBePositive {
            get {
                return ResourceManager.GetString("Error_Plan_TotalFeesMustBePositive", resourceCulture);
            }
        }
    }
}
