//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drosy.Domain.Shared.ErrorComponents.Plans.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_Plan_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_Plan_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drosy.Domain.Shared.ErrorComponents.Plans.Resources.ErrorMessages.Plan.en", typeof(ErrorMessages_Plan_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database constraint was violated while processing the plan..
        /// </summary>
        internal static string Error_Plan_ConstraintViolation {
            get {
                return ResourceManager.GetString("Error_Plan_ConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one day of the week must be selected..
        /// </summary>
        internal static string Error_Plan_DaysOfWeekRequired {
            get {
                return ResourceManager.GetString("Error_Plan_DaysOfWeekRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required..
        /// </summary>
        internal static string Error_Plan_EndDateRequired {
            get {
                return ResourceManager.GetString("Error_Plan_EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time of the session is required..
        /// </summary>
        internal static string Error_Plan_EndSessionRequired {
            get {
                return ResourceManager.GetString("Error_Plan_EndSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before end date..
        /// </summary>
        internal static string Error_Plan_InvalidDateRange {
            get {
                return ResourceManager.GetString("Error_Plan_InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan period must be greater than zero..
        /// </summary>
        internal static string Error_Plan_InvalidPeriod {
            get {
                return ResourceManager.GetString("Error_Plan_InvalidPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be before end time..
        /// </summary>
        internal static string Error_Plan_InvalidSessionTimeRange {
            get {
                return ResourceManager.GetString("Error_Plan_InvalidSessionTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a plan that has registered students..
        /// </summary>
        internal static string Error_Plan_PlanCannotDeleteWithStudents {
            get {
                return ResourceManager.GetString("Error_Plan_PlanCannotDeleteWithStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plan is inactive and cannot be used..
        /// </summary>
        internal static string Error_Plan_PlanInactive {
            get {
                return ResourceManager.GetString("Error_Plan_PlanInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested plan was not found..
        /// </summary>
        internal static string Error_Plan_PlanNotFound {
            get {
                return ResourceManager.GetString("Error_Plan_PlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the plan. Please try again..
        /// </summary>
        internal static string Error_Plan_PlanSaveFailure {
            get {
                return ResourceManager.GetString("Error_Plan_PlanSaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plan type is not supported..
        /// </summary>
        internal static string Error_Plan_PlanTypeNotSupported {
            get {
                return ResourceManager.GetString("Error_Plan_PlanTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another plan with the same session time exists on the selected days..
        /// </summary>
        internal static string Error_Plan_SessionTimeConflict {
            get {
                return ResourceManager.GetString("Error_Plan_SessionTimeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required..
        /// </summary>
        internal static string Error_Plan_StartDateRequired {
            get {
                return ResourceManager.GetString("Error_Plan_StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time of the session is required..
        /// </summary>
        internal static string Error_Plan_StartSessionRequired {
            get {
                return ResourceManager.GetString("Error_Plan_StartSessionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total fees must be greater than zero..
        /// </summary>
        internal static string Error_Plan_TotalFeesMustBePositive {
            get {
                return ResourceManager.GetString("Error_Plan_TotalFeesMustBePositive", resourceCulture);
            }
        }
    }
}
