//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drosy.Domain.Shared.ErrorComponents.Sesstions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_Session {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_Session() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drosy.Domain.Shared.ErrorComponents.Sesstions.Resources.ErrorMessages.Session", typeof(ErrorMessages_Session).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النطاق الزمني المحدد للجلسة غير صالح..
        /// </summary>
        internal static string Error_Session_InvalidTimeRange {
            get {
                return ResourceManager.GetString("Error_Session_InvalidTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون توقيتات الجلسة ضمن التاريخ المتوقع..
        /// </summary>
        internal static string Error_Session_OutsideExpectedDate {
            get {
                return ResourceManager.GetString("Error_Session_OutsideExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على خطة مرتبطة بهذه الجلسة..
        /// </summary>
        internal static string Error_Session_PlanNotFound {
            get {
                return ResourceManager.GetString("Error_Session_PlanNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الجلسة..
        /// </summary>
        internal static string Error_Session_SessionNotFound {
            get {
                return ResourceManager.GetString("Error_Session_SessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  يجب أن يكون وقت بدء الجلسة قبل وقت انتهائها..
        /// </summary>
        internal static string Error_Session_StartAfterEnd {
            get {
                return ResourceManager.GetString("Error_Session_StartAfterEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجد جلسة بالفعل في نفس الفترة الزمنية المحددة..
        /// </summary>
        internal static string Error_Session_TimeOverlap {
            get {
                return ResourceManager.GetString("Error_Session_TimeOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الجلسة مطلوب..
        /// </summary>
        internal static string Error_Session_TitleRequired {
            get {
                return ResourceManager.GetString("Error_Session_TitleRequired", resourceCulture);
            }
        }
    }
}
